### ISSUE TITLE
Remove (on some level) the calculation from the UI

### ISSUE THREAD

**Issue by Luc1eSky** [Luc1eSky/financial_literacy_game#1]
Remove the calculation in the game at a certain point. The code for the method to create the hint message is in the utils.dart file and the info is displayed in the UI on the Investment Dialog (investment_dialog.dart file). In order to remove it from being displayed, we can just comment out this section of the code

<img width="569" alt="image" src="https://github.com/Luc1eSky/financial_literacy_game/assets/26046283/a9b527a4-7aad-4ca5-ab7a-575939bcd046">

**Comment by Paolaaqh1202** [comment]
Hi everyone!
I created a branch and commented on that chunk of code in the utils.dart file:

<img width="905" alt="Screenshot 2024-03-29 at 10 35 25 AM" src="https://github.com/Luc1eSky/financial_literacy_game/assets/158004829/4874c77c-1537-4573-9795-457f7324bb35">

However, I have some doubts about the message, because I went through the whole game as a player and the message didn't pop up.

**Comment by Luc1eSky** [comment]
Hi Paola,

I am a bit unsure about the issue you are seeing, if you comment out that part of the code it is no longer visible, so it is expected. If you want to introduce some logic that the hint is only applied for a few rounds or at a specific level, you would have to create a condition when the hint should be visible in the code.

**Comment by Paolaaqh1202** [comment]
Hi Lucie,
Got it, thanks. I think I'll hold on to this so that in the meeting this Friday we can talk more about the issue itself. I want to have it completely clear. Like for example, at what levels should the hint be displayed and what ones no.

**Comment by awhobbs** [comment]
Totally fine to wait until Friday to discuss with the whole group, but I'd
suggest we remove the hint after the first level (starting with level 2).

**Comment by Luc1eSky** [comment]
has been implemented
